[icons]
# font awesome
TelegramDesktop = "ï‹†"
Firefox = "ï‰©"
Alacritty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
# smile emoji
MyNiceProgram = "ðŸ˜›"

[aliases]
TelegramDesktop = "Telegram"
"Org.gnome.Nautilus" = "Nautilus"

[general]
separator = " î‚± "
